[package]
name = "class06"
version = "0.1.0"
authors = ["EzanAsif <ezanasif1972@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
reqwest = "0.9.22"
rustc-serialize = "0.3.24"